version: '3'

services:
  pipeline:
    image: pipeline
    container_name: pipeline
    build:
      context: ./
      dockerfile: ./docker/pipeline/Dockerfile
    volumes:
      - ./:/app
      - ./logs:/var/log
    environment:
      API_KEY: ${API_KEY}
      LOCAL_TZ: ${LOCAL_TZ}
      COIN_ID: ${COIN_ID}
      CRON_LOG_FILE: /var/log/cron.log
      PIPELINE_LOG_FILE: /var/log/pipeline.log

    

